### ISSUE TITLE
fails to connect (webQuery)

### ISSUE THREAD

**Issue by xedom** [alezm00/TS-troller#1]
**Describe the bug**
The server fails to connect to the teamspeak webQuery

**To Reproduce**

0. Start/Create a teamspeak server version 3.12.0
1. Download git repo
2. Enter into the repo folder
4. Run `npm i`
5. Run `npm start`
6. Open the browser and go to `http://localhost:3000/`
7. Put in the input "Server link for requests": `http://localhost:10080/`
8. Put in the input "Insert api key": your apikey
9. Press "Send"
10. See error : `request to http://localhost:10080/serverlist failed, reason: connect ECONNREFUSED 127.0.0.1:10080 | (1)`

**Screenshots**
![https://imgur.com/a/IY3sVG2](https://i.imgur.com/jHInXm4.png)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser firefox

**Comment by alezm00** [comment]
Is the server started with this parameter? `query_protocols=raw,ssh,http,https`

**Comment by xedom** [comment]
thanks, now it works :)
